### PR TITLE
Remove pending requests on session expiration

### LINKED ISSUE #1343: Unactionable request appearing on sessionRequestPublisher when upgrading from 1.10.0 -> 1.18.4
**Describe the bug**
Upgraded from 1.10.0 -> 1.18.4 and everytime I ran my app via xcode, I kept getting an invalid request coming through (for an account not currently on this simulator, but was previously). I downgraded back to 1.10.0, it stopped showing. I cleared all sessions, pairings etc, killed and reopened the app, everything was fine. Upgraded to 1.18.4 again and the request shows up again. I'm unable to reject it, as I get an error saying no matching topic was found. I'm now blocked from upgrading the version as my app gets stuck showing loading spinners and errors everytime its opened

Request id: `1705070997947507`
Request topic: `82a8d2dd571e3a7ccf253ff6b08b2536309655a92c3cffced0b2de448b0c3dca`

Screenshot of it incoming:
Screenshot 2024-04-12 at 13 57 59

Screenshot of console log showing unable to reject error
Screenshot 2024-04-12 at 12 42 59

**SDK Version**
 - Client: Swift
 - Version: 1.10.0 upgrading to 1.18.4

**To Reproduce**
Unknown how I got into this state. Must have been a request that wasn't rejected/approved properly a long time ago, I didn't generate any such request today or yesterday at least. None of the inbuilt timeouts are working as this has been happening now for several hours

### PR DESCRIPTION
**Pull request by jackpooleywc**
# Description

This is a follow up to https://github.com/WalletConnect/WalletConnectSwiftV2/pull/1353.

In addition to clearing stale requests on initialisation, this PR also makes sure requests related to the session are also cleared when the session expires.

Resolves #1343

## How Has This Been Tested?

> [!NOTE]
> This has not yet been tested against the bug as I am still unable to reproduce, this will be tested before merging.

## Due Dilligence

* [ ] Breaking change
* [ ] Requires a documentation update

### CODE REVIEW

File: Tests/WalletConnectSignTests/SessionEngineTests.swift [hunk 1]
```diff
@@ -62,4 +63,56 @@ final class SessionEngineTests: XCTestCase {
...
+        let request = RPCRequest.stubRequest(
+            method: "method",
+            chainId: Blockchain("eip155:1")!,
+            expiry: UInt64(Date().timeIntervalSince1970)
+        )
+        
+        networkingInteractor.requestPublisherSubject.send(
+            (expectedTopic, request, Data(), Date(), "")
+        )
+
```
Comment (llbartekll) [inline Tests/WalletConnectSignTests/SessionEngineTests.swift:108]: I wonder if we need this part

**Review by llbartekll — APPROVED** [review]

File: Tests/WalletConnectSignTests/SessionEngineTests.swift (hunk 1 above)
Comment (jackpooleywc) [reply Tests/WalletConnectSignTests/SessionEngineTests.swift]: removed ✅
