### PR TITLE
#248 fix crash on pair

### LINKED ISSUE #248: Fix potential crash on malformed QR code scan
**Describe the bug**
`PairEngine` FIXME tag.

**Expected behavior**
The SDK must not crash when scanning a malformed QR code.

### PR DESCRIPTION
**Pull request by llbartekll**
- fix crash on pair but does not override key in keychain close #248
- sync develop with main

### CODE REVIEW

File: Sources/WalletConnectSign/Engine/Controller/PairEngine.swift [hunk 1]
```diff
@@ -20,8 +20,8 @@ actor PairEngine {
         }
         var pairing = WCPairing(uri: uri)
         try await networkingInteractor.subscribe(topic: pairing.topic)
-        let symKey = try! SymmetricKey(hex: uri.symKey) // FIXME: Malformed QR code from external source can crash the SDK
-        try! kms.setSymmetricKey(symKey, for: pairing.topic)
+        let symKey = try SymmetricKey(hex: uri.symKey)
+        try kms.setSymmetricKey(symKey, for: pairing.topic)
```
Comment (flypaper0) [inline Sources/WalletConnectSign/Engine/Controller/PairEngine.swift:24]: we still need key replacement logic, right?

**Review by flypaper0 — APPROVED** [review]

File: Sources/WalletConnectSign/Engine/Controller/PairEngine.swift (hunk 1 above)
Comment (llbartekll) [reply Sources/WalletConnectSign/Engine/Controller/PairEngine.swift:24]: correct,
it's this one:
https://github.com/WalletConnect/WalletConnectSwiftV2/issues/360
